#!/bin/bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get julienloizelet/ddev-playwright
#
# This file comes from https://github.com/julienloizelet/ddev-playwright
#
## Description: Install playwright in PLAYWRIGHT_TEST_DIR
## Usage: playwright-install
## Example: "ddev playwright-install"
cd /var/www/html || exit 1
cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

export PLAYWRIGHT_BROWSERS_PATH=0
PRE="sudo -u pwuser PLAYWRIGHT_BROWSERS_PATH=0 "

if [ -e "/var/www/html/package-lock.json" ]; then
  $PRE npm install
  $PRE npm init playwright@latest -y
else
  $PRE yarn install
  $PRE yarn playwright install --with-deps
fi

# Conditionally copy an .env file if an example file exists
[ -f .env.example ] && [ ! -f .env ] && $PRE cp -n .env.example .env; exit 0
