#!/bin/bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get julienloizelet/ddev-playwright
#
# This file comes from https://github.com/julienloizelet/ddev-playwright
#
cd /var/www/html || exit 1
cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

export PLAYWRIGHT_BROWSERS_PATH=/var/www/html/${PLAYWRIGHT_TEST_DIR}/pw-browsers
PRE="sudo -u pwuser PLAYWRIGHT_BROWSERS_PATH=${PLAYWRIGHT_BROWSERS_PATH} "

$PRE yarn install
$PRE yarn playwright install --with-deps
$PRE cp -n .env.example .env || true
