#!/usr/bin/env bash
#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev add-on get julienloizelet/ddev-playwright
#
# This file comes from https://github.com/julienloizelet/ddev-playwright
#
## Description: Init playwright in PLAYWRIGHT_TEST_DIR
## Usage: playwright-init --pm [npm|yarn]
## Example: "ddev playwright-init --pm yarn"

function display_help() {
    echo "Usage: $0 --pm [yarn|npm]"
    echo "Example: $0 --pm yarn"
    exit 1
}

# Default package manager is not set
PACKAGE_MANAGER=""

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --pm) PACKAGE_MANAGER="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; display_help ;;
    esac
    shift
done

# Check if package manager is specified and valid
if [[ -z "$PACKAGE_MANAGER" ]] || ! { [[ "$PACKAGE_MANAGER" == "yarn" ]] || [[ "$PACKAGE_MANAGER" == "npm" ]]; }; then
    echo "Warning: Package manager should be specified with --pm and be one of 'yarn' or 'npm'."
    echo "Defaulting to yarn"
    PACKAGE_MANAGER="yarn"
fi

cd /var/www/html || exit 1
cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

export PLAYWRIGHT_BROWSERS_PATH=0

if [[ $PACKAGE_MANAGER == "npm" ]]; then
    npm init playwright@latest
elif [[ $PACKAGE_MANAGER == "yarn" ]]; then
    yarn create playwright
fi

# Conditionally copy an .env file if an example file exists
[ -f .env.example ] && [ ! -f .env ] && cp -n .env.example .env; exit 0
